version: "3.3"
services:
  eventer:
    image: ruby:2.7.5 #kleer-la/keventer3 
    container_name: eventer
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    tty: true
    working_dir: /app
