require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/service_areas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ServiceArea. As you add validations to ServiceArea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ServiceArea.create! valid_attributes
      get service_areas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      service_area = ServiceArea.create! valid_attributes
      get service_area_url(service_area)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_service_area_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      service_area = ServiceArea.create! valid_attributes
      get edit_service_area_url(service_area)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ServiceArea" do
        expect {
          post service_areas_url, params: { service_area: valid_attributes }
        }.to change(ServiceArea, :count).by(1)
      end

      it "redirects to the created service_area" do
        post service_areas_url, params: { service_area: valid_attributes }
        expect(response).to redirect_to(service_area_url(ServiceArea.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ServiceArea" do
        expect {
          post service_areas_url, params: { service_area: invalid_attributes }
        }.to change(ServiceArea, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post service_areas_url, params: { service_area: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested service_area" do
        service_area = ServiceArea.create! valid_attributes
        patch service_area_url(service_area), params: { service_area: new_attributes }
        service_area.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the service_area" do
        service_area = ServiceArea.create! valid_attributes
        patch service_area_url(service_area), params: { service_area: new_attributes }
        service_area.reload
        expect(response).to redirect_to(service_area_url(service_area))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        service_area = ServiceArea.create! valid_attributes
        patch service_area_url(service_area), params: { service_area: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested service_area" do
      service_area = ServiceArea.create! valid_attributes
      expect {
        delete service_area_url(service_area)
      }.to change(ServiceArea, :count).by(-1)
    end

    it "redirects to the service_areas list" do
      service_area = ServiceArea.create! valid_attributes
      delete service_area_url(service_area)
      expect(response).to redirect_to(service_areas_url)
    end
  end
end
